export default [
  {
    name: 'The C Programming Language',
    ISBN: '12345644890',
    author: 'John Doe',
    price: 280,
    pages: 250,
    category: 'Programming',
    img: 'images/1.jpg',
  },
  {
    name: 'Eloquent JavaScript',
    ISBN: '12345677790',
    author: 'John Doe',
    price: 120,
    pages: 30,
    category: 'Programming',
    img: 'images/2.png',
  },
  {
    name: 'The Complete Book on Angular',
    ISBN: '12345621890',
    author: 'John Doe',
    price: 100,
    pages: 550,
    category: 'Programming',
    img: 'images/3.jpg',
  },
  {
    name: 'Head First Java',
    ISBN: '12345249890',
    author: 'John Doe',
    price: 150,
    pages: 400,
    category: 'Programming',
    img: 'images/4.jpg',
  },
  {
    name: 'Node.js in Action',
    ISBN: '12345620890',
    author: 'John Doe',
    price: 200,
    pages: 320,
    category: 'Programming',
    img: 'images/5.png',
  },
  {
    name: 'Full Stack React',
    ISBN: '12345670890',
    author: 'John Doe',
    price: 140,
    pages: 350,
    category: 'Programming',
    img: 'images/6.jpg',
  },
  {
    name: 'Vue.js in Action',
    ISBN: '12345677990',
    author: 'John Doe',
    price: 180,
    pages: 45,
    category: 'Programming',
    img: 'images/7.jpg',
  },
  {
    name: 'Programming Python',
    ISBN: '12345636890',
    author: 'John Doe',
    price: 220,
    pages: 380,
    category: 'Programming',
    img: 'images/8.jpg',
  },
  {
    name: 'C# in a Nutshell',
    ISBN: '12345643890',
    author: 'John Doe',
    price: 300,
    pages: 950,
    category: 'Programming',
    img: 'images/9.jpg',
  },
];
